### ISSUE TITLE
Needs "glibcxx_3.4.22" possibly from gcc 6.3

### ISSUE THREAD

**Issue by ojnc** [lakshayg/tensorflow-build-archived#1]
Gave a lot of problems
mainly libstdc++.so.6: version `GLIBCXX_3.4.22' not found 
also libstdc++.so.6: version `GLIBCXX_3.4.21' not found

GLIBCXX_3.4.21 got resolved when when I tried
LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libstdc++.so.6" python jncpy/dee2keras.py

then GLIBCXX_3.4.22 appeared
I took a risk and installed based on 
https://askubuntu.com/questions/746369/how-can-i-install-and-use-gcc-6-on-xenial
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-6 g++-6

Lakshay Garg great job
Only please mention the GCC requirements as even on 16.04 gcc 5.4 is default

If possible plaese do another build on a clean install ubuntu 16.04  with all standard defaults
then more people will be benefited

Also installation command may be mentioned
pip install --ignore-installed --upgrade ~/Downloads/tensorflow-1.1.0-cp36-cp36m-linux_x86_64.whl

**Comment by lakshayg** [comment]
Thanks for bringing this to my notice. This was compiled using GCC 6.3 on Manjaro Linux. I will try and build a version with gcc 5.x
