### ISSUE TITLE
Single line installation for Readme

### ISSUE THREAD

**Issue by adler-j** [lakshayg/tensorflow-build-archived#11]
The packages can be installed via e.g.

``` 
pip install https://raw.githubusercontent.com/lakshayg/tensorflow-build/master/tensorflow-1.4.0rc1-cp36-cp36m-linux_x86_64.whl
```

perhaps this should be the recommended method for the readme, or at least an option?

**Comment by lakshayg** [comment]
Hi alder-j, yes you are right that the packages can be installed in this manner. Would you be interested in sending a pull request?
