### ISSUE TITLE
tf `v.1.4.1` mac-mini does not support `AVX2`

### ISSUE THREAD

**Issue by mixuala** [lakshayg/tensorflow-build-archived#21]
Hello,

I'm using your `1.2.1` MacOS build but now I'm running into random version problems with tensorboard.  I'd like to try `1.4.1` but the mac-mini does not support `AVX2` .  Can you build a `1.4.1` to that spec? Or, send me a link on how to build one myself?  

Many thanks!

**Comment by lakshayg** [comment]
I have uploaded the wheels. HTH.

| TF       | HW  | OS           | GCC              | Python      | Supports                                  |                                                                                                                         |
|----------|-----|--------------|------------------|-------------|-------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|
| 1.4.1    | CPU | macOS Sierra | clang-900.0.39.2   | 2.7.13    | AVX, SSE4.1, SSE4.2                       | [Download](https://github.com/lakshayg/tensorflow-build/releases/download/v1.4.1-macosx_10_12-py27-py36-avx-sse41-sse42/tensorflow-1.4.1-cp27-cp27m-macosx_10_12_intel.whl) |
| 1.4.1    | CPU | macOS Sierra | clang-900.0.39.2   | 3.6.1       | AVX, SSE4.1, SSE4.2                       | [Download](https://github.com/lakshayg/tensorflow-build/releases/download/v1.4.1-macosx_10_12-py27-py36-avx-sse41-sse42/tensorflow-1.4.1-cp36-cp36m-macosx_10_12_x86_64.whl) |

**Comment by mixuala** [comment]
Thanks! but I didn't notice this in time so I tried to build it myself. it was not so hard. here is what I did based on the docs found at https://www.tensorflow.org/install/install_sources

```
cd [parent dir]
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
git checkout tags/v1.4.1 -b r1.4

sudo pip install six numpy wheel 
brew cask install caskroom/versions/java8
brew install coreutils bazel
brew upgrade bazel

./configure
bazel build --config=opt --incompatible_load_argument_is_label=false //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
sudo pip install /tmp/tensorflow_pkg/tensorflow-1.4.1-cp36-cp36m-macosx_10_7_x86_64.whl

```

**Comment by lakshayg** [comment]
Great!
