### ISSUE TITLE
raise BadZipfile, "File is not a zip file" BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by akumar14** [lakshayg/tensorflow-build-archived#25]
I am getting this error while installing tensorflow on a system with anaconda (python 2.7)  + p6000 GPUs + Cuda 8 + Cudnn  7.5 .

**Comment by lakshayg** [comment]
Which binary are you using?

**Comment by akumar14** [comment]
If by binary you mean the tensorflow binaries , I am using this:

https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.5.0-cp27-none-linux_x86_64.whl

**Comment by lakshayg** [comment]
I see, however I am not sure how can I help if this is not related to the binaries in this repo. Perhaps opening an issue in the tensorflow repo would be more helpful.

You can try also compiling TF on your machine.

Please let me know if there is anything I can do.

**Comment by 631068264** [comment]
Hello @akumar14 
I met similar problem too .`zipfile.BadZipFile: File is not a zip file` Use Py3.6  OSX. I guess you may use `pip install --ignore-installed --upgrade "Download URL"` to install . Just try to download the `whl` and use `pip install --ignore-installed --upgrade /path/to/binary.whl` it work for me .
