### ISSUE TITLE
TF 1.6.0 Ubuntu 16.04 Python 2.7.2 GCC 5.4 AVX2 FMA

### ISSUE THREAD

**Issue by akaniklaus** [lakshayg/tensorflow-build-archived#27]
Can you please add binaries for the specified version? Thanks.

**Comment by lakshayg** [comment]
Here it is: [Download](https://github.com/lakshayg/tensorflow-build/releases/download/v1.6.0-ubuntu_16_04-py27-avx-avx2-fma-sse41-sse42/tensorflow-1.6.0-cp27-cp27mu-linux_x86_64.whl)
