### ISSUE TITLE
also comes to ''tensorflow.python.framework.fast_tensor_util' does not match'

### ISSUE THREAD

**Issue by tengshaofeng** [lakshayg/tensorflow-build-archived#29]
hi， first thanks for your sharing.
are these tensorflows gpu version?
i test the tensorflow-1.4.0, and it is cpu version. do you have gpu version?

**Comment by lakshayg** [comment]
I don't have any GPU versions of TF in this repo, however, you can find some at https://github.com/mind/wheels
