### ISSUE TITLE
BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by JohnV7** [lakshayg/tensorflow-build-archived#3]
I get this error message
> BadZipfile: File is not a zip file

when trying to install following wheel:
tensorflow-1.2.0rc1-cp27-cp27mu-linux_x86_64.whl

**Comment by lakshayg** [comment]
Could you please post your operating system, python and GCC versions.

**Comment by JohnV7** [comment]
I have exactly the configuration for which the wheel was designed according to the information given in the README.txt

> Ubuntu 16.04, GCC 5.4.0, Python 2.7.12

**Comment by lakshayg** [comment]
Can you run this command `sha256sum tensorflow-1.2.0rc1-cp27-cp27mu-linux_x86_64.whl`. You should get the following output `25e7f9f9a8394c82dd2868fd126bed30b147f66bdf73ab800339b5b3c03e8201`. If not then your download is probably corrupted.

**Comment by JohnV7** [comment]
This was the problem. I downloaded the file with wget, because I don't know if you can download individual files with git. 
Now I managed to install it (using git clone ), but importing tensorflow gives me this error:

> Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mock was given, but was not able to be found.

**Comment by lakshayg** [comment]
Try upgrading the distribute module: `pip install --upgrade distribute`. BTW you don't need to clone the entire repo in order to use just one file, you can use:

```
pip install --upgrade https://github.com/lakshayg/tensorflow-build/raw/master/tensorflow-1.2.0rc1-cp27-cp27mu-linux_x86_64.whl
```

**Comment by JohnV7** [comment]
pip install --upgrade distribute gives me this
> "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RhMcyd/distribute/

**Comment by lakshayg** [comment]
Okay, try this: `sudo easy_install distribute`

**Comment by JohnV7** [comment]
the last instruction worked, but I still get the same message importing tensorflow.

**Comment by lakshayg** [comment]
Can you try doing
```
pip install --upgrade --ignore-installed tensorflow-1.2.0rc1-cp27-cp27mu-linux_x86_64.whl
```
Note the --ignore-installed flag

**Comment by JohnV7** [comment]
yes, I had tried this already. I also tried pip uninstall tensorflow first and then the above command, but it still does not work

**Comment by lakshayg** [comment]
See this thread: https://github.com/tensorflow/tensorflow/issues/7980

**Comment by JohnV7** [comment]
This worked:
> pip install -U protobuf==3.0.0b2

Many thanks! 

Let's see now if I get any faster with my CPU.

**Comment by lakshayg** [comment]
Glad it worked! Closing this issue.
