### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by HaoyangFan96** [lakshayg/tensorflow-build-archived#36]
Hi I am new to tensorflow, and wonder if there is a pre-build tensorflow (CPU) 1.9.0 for Ubuntu 18.04, Python 3.6.5

Thanks

**Comment by lakshayg** [comment]
Hi, I can try to build TF for Ubuntu 18.04, Python 3.6.5 next week. Will update when done.

On Wed, 1 Aug 2018 at 17:29 HaoyangFan96 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi I am new to tensorflow, and wonder if there is a pre-build tensorflow (CPU) 1.9.0 for Ubuntu 18.04, Python 3.6.5

Thanks

**Comment by lakshayg** [comment]
Hi, I can try to build TF for Ubuntu 18.04, Python 3.6.5 next week. Will update when done.

**Comment by lakshayg** [comment]
Done

**Comment by HaoyangFan96** [comment]
@lakshayg  Thanks for the help.

However, there seems like to have a problem with this tensorflow installation:

After installation, when I verify it 

```
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2018-08-09 11:07:23.104969: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use FMA instructions, but these aren't available on your machine.
Aborted (core dumped)

```

My machine doesn't support FMA, but it does support AVX2

Any idea on how to solve it?

**Comment by lakshayg** [comment]
The only way to solve this issue would be to recompile the binaries without FMA. The compilation process is quite simple and well described on the TF website. You should give it a try and write back in case you face any issues.
