### ISSUE TITLE
Tensorflow 1.10 released

### ISSUE THREAD

**Issue by rlan** [lakshayg/tensorflow-build-archived#37]
Thank you for sharing your builds.

**Comment by mknippen** [comment]
+1

**Comment by lakshayg** [comment]
https://github.com/lakshayg/tensorflow-build/releases/tag/tf1.10.0-ubuntu18.04-py36-py27

**Comment by rlan** [comment]
@lakshayg Thanks! Would you mind releasing an Ubuntu 16.04 version? We are still using that.

**Comment by lakshayg** [comment]
https://github.com/lakshayg/tensorflow-build/releases/tag/tf1.10.0-ubuntu16.04-py35-py27

**Comment by rlan** [comment]
Thank you @lakshayg !

**Comment by iedmrc** [comment]
Also version 1.10 release for macos high sierra would be great. Thanks!
