### ISSUE TITLE
AVX512F

### ISSUE THREAD

**Issue by jimgros** [lakshayg/tensorflow-build-archived#38]
This worked great! Thanks
(python 3.6.6 
tf 1.9.0 
ubuntu 16.04)

I am still seeing one message:
`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F`
Do you think you could incorporate one as well?
(PS using AWS instances, so this might be useful for a few more people).

**Comment by lakshayg** [comment]
https://github.com/lakshayg/tensorflow-build/releases/tag/tf1.10.0-ubuntu16.04-py36-avx512f

**Comment by jimgros** [comment]
That worked. Thanks a lot.
