### ISSUE TITLE
Could you build a no-cuda version for macOS?

### ISSUE THREAD

**Issue by elder-frog** [lakshayg/tensorflow-build-archived#4]
Thank you so much.

**Comment by lakshayg** [comment]
@wwh2259253 I currently don't have any plans for building TF for macOS as I do not have access to a macOS machine. You might want to visit https://github.com/yaroslavvb/tensorflow-community-wheels to see if someone has uploaded a wheel for your platform.

**Comment by lakshayg** [comment]
I finally got access to a macOS machine. In case you still need it, I have compiled a wheel for macOS with python 2.7

**Comment by elder-frog** [comment]
@lakshayg 
Thank you very much for your help
