### ISSUE TITLE
tensorflow-build makes tensorflow slow how to uninstall?

### ISSUE THREAD

**Issue by hipa777** [lakshayg/tensorflow-build-archived#40]
Hi 

I have installed tensorflow-1.4.1-cp27-cp27m-macosx_10_12_intel.whl in a macOS sierra successfully, however it seems that it makes everything slow down, when I run a handwritten digit recognition script it seems that it gets held... never finish, previously it was working and I was just getting the warning about "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA"

I did the same for a PC wth ubuntu  16.04 installing tensorflow-1.6.0-cp27-cp27mu-linux_x86_64.whl and have the same issue it seems that it gets held... never finish 

How can I uninstall this application?

thanks
Aaron

**Comment by lakshayg** [comment]
This is weird. I would normally expect a 20-30% speedup. Anyway, to uninstall
```
pip uninstall tensorflow
```

**Comment by hipa777** [comment]
Can be an issue with the tensorflow version I'm using? 
tensorflow Version: 1.10.1, and I notice that the .whl files are tagged 1.6.0

**Comment by hipa777** [comment]
Well, I can confirm the previous guess... I installed tensorflow 1.6.0 and everything is working properly and I can see a slightly improvement on speed. Thanks

**Comment by lakshayg** [comment]
I don't think this should have anything to do with the TF version. The versions you used were 1.4.1 on macOS and 1.6.0 on Ubuntu. Have you tried the latest versions?

**Comment by hipa777** [comment]
well I tried with 1.10.1 on ubuntu and had the same issue, then downgrade to 1.6.0 and it works fine
