### ISSUE TITLE
Tensorflow.js

### ISSUE THREAD

**Issue by Mr-Magnificent** [lakshayg/tensorflow-build-archived#41]
I wish to create a custom build of tensorflow.js but to I need SSE4.1 and SSE4.2 bindings. Will these port to tensorflow.js. If not, can you suggest a method?

**Comment by lakshayg** [comment]
Do you need to "build" tensorflow.js? I looked at the tensorflow.js website and couldn't find any build instructions. I am not familiar with the javascript ecosystem so maybe I missed something.

**Comment by Mr-Magnificent** [comment]
Since tensorflow.js is a new environment it lacks the documentation and help online as compared to tensorflow for python. Tensorflow.js is not optimized for my cpu and your "binding" were pointed as solution for python ones. I was wondering that if they port to tensorflow.js also?

**Comment by lakshayg** [comment]
I looked around a little more and found that tfjs-node uses libtensorflow. The ".whl" files in this repo are python-only. These cannot be used for tfjs but what you can do is to compile libtensorflow from source with the -march=native flag and that should solve your issue.

```
bazel build --config=monolithic //tensorflow/tools/lib_package:libtensorflow
```
