### ISSUE TITLE
Mojave build needed sudo to install

### ISSUE THREAD

**Issue by paulwhitby** [lakshayg/tensorflow-build-archived#43]
Not an issue but an observation. 
First, many thanks for providing these custom builds! 
I have MacOS Mojave, & the specified versions of clang & python. pip3 install as specified failed, but sudo sorted it. I don't know if that was right but it certainly works fine now.

**Comment by lakshayg** [comment]
This is perfectly normal. pip defaults to installing python packages to a system directory (such as `/usr/local/lib/python3.4`). This requires root access. You can use the `--user` flag to make pip install packages in your home directory instead, which doesn't require any special privileges.

```
pip install --ignore-installed --upgrade "Download URL" --user
```

You can run the following command to see where `--user` flag installs the package.

```
python -c "import site; print(site.USER_SITE)"
```
