### ISSUE TITLE
Runetime Warning in tensorflow with Raspberry Pi 1 model B

### ISSUE THREAD

**Issue by Ragnarok1988** [lakshayg/tensorflow-build-archived#45]
When i want to use tensorflow on my raspberry pi 1, I have the following problem:
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
return f(*args, **kwds)

I have Python 3.5.3 and i install tensorflow (1.11) with the following command:
sudo python3 -m pip install --no-cache-dir tensorflow

I cant use your builds, because i have raspbian not ubuntu:( and when i try to use the linux version, i got this:
tensorflow-1.11.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.

Thx for the help!

**Comment by lakshayg** [comment]
Do you mean that you have an issue with the stock tensorflow? If so, I am not sure how I can help. Looking at the error message, I **guess** it has something to do with some sort of incompatibility between python 3.4 and 3.5. You can try doing `python3 -m pip install --ignore-installed --upgrade tensorflow` and if you continue facing this issue then you can try to build from source https://www.tensorflow.org/install/source_rpi

**Comment by Ragnarok1988** [comment]
Thank you for your quick answer, Yes, it is the stock tensorflow, i think that my rapsperry pi 1 is so old, that they dont testing and optimizing tensorflow and python for that:( Maybe i should get a new one:)
Build from source is problematic for me, because i have windows home version, and its not good for the docker.
Thank you for your help again!
