### ISSUE TITLE
Tensorflow 1.12 for MacOS Hight Sierra & Ubuntu 18

### ISSUE THREAD

**Issue by oldani** [lakshayg/tensorflow-build-archived#47]
Could you please upload Tensorflow 1.12 for MacOS Hight Sierra & Ubuntu 18?

**Comment by lakshayg** [comment]
I won't be able to upload for High Sierra as I don't have a machine with High Sierra installed. I could give Ubuntu 18 a try but won't be able to do it before late next week.

**Comment by lakshayg** [comment]
I have uploaded the binaries for ubuntu 18.04
