### ISSUE TITLE
Can you please upload tf 1.12 with AVX2, AVX512F FMA for Ubuntu 18.04 ?

### ISSUE THREAD

**Issue by natidani** [lakshayg/tensorflow-build-archived#48]

**Comment by lakshayg** [comment]
What version of python are you on? Also, did you try 
https://github.com/lakshayg/tensorflow-build/releases/download/tf1.10.0-ubuntu16.04-py36-avx512f/tensorflow-1.10.0-cp36-cp36m-linux_x86_64.whl?

**Comment by natidani** [comment]
python 3.6.
the link is for Ubuntu 16.04 and tf 1.10.0- and not match to my needs.

**Comment by lakshayg** [comment]
Just those 3 flags or avx, sse4.1, sse4.2 as well? Also, You should still give that whl a try unless there's some TF1.12 specific stuff you want to use.

**Comment by natidani** [comment]
Just those 3 flags. i tried and this whl doesnt work.

**Comment by lakshayg** [comment]
There you go: 
https://github.com/lakshayg/tensorflow-build/releases/download/tf1.12.0-ubuntu18.04-py3-avx512f/tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl
