### ISSUE TITLE
could you compile for older system

### ISSUE THREAD

**Issue by duhd1993** [lakshayg/tensorflow-build-archived#53]
Could you compile this for Ubuntu 16.04?

1.12.0 | CPU | Ubuntu 18.04 | 7.3 | 3.6.5 | FMA, AVX2, AVX512F | Download

It requires Glibc 2.27, but I'm only able to compile glibc 2.23 on this old Redhat 6.1 system.

Currently I'm able to use

1.10.0 | CPU | Ubuntu 16.04 | 5.4 | 3.6.6 | FMA, AVX, AVX2, SSE4.1, SSE4.2, AVX512F | Downlod

I suppose if it could be run on Ubuntu 16.04, I can get it working on my system.

Other options don't include AVX512F which the CPUs support. And I want to use Python 3. 

BTW, I'm able to use conda build of Tensorflow 1.12. But they don't enable all the CPU features.

**Comment by lakshayg** [comment]
Give this script a try: https://github.com/lakshayg/tensorflow-build/blob/master/build_tf_ubuntu.sh and let me know if you face any issues.

**Comment by duhd1993** [comment]
Thank you. I won't be able to run the script since I'm using Redhat 6.1. It seems to be automating the compiling process. I've already been trying to compile Tensorflow from source. Many problems during compiling. For example, external/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:30:18: fatal error: ares.h: No such file or directory. This is the error I just saw.

I might want to compile on other computer or virtual machine.

**Comment by lakshayg** [comment]
I just noticed TF 1.13 was released. Will compile this config while compiling those binaries

**Comment by duhd1993** [comment]
Thank you so much!

**Comment by duhd1993** [comment]
I just managed to compile 1.13 for my system. It's really a struggle. I can share the wheel if anyone need. The cpus are Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz, all flags like avx2 avx512 are turned on.  it can be used in glibc 2.12 environment.

BTW, I got these output
"""
2019-02-25 02:05:31.534754: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192495000 Hz
2019-02-25 02:05:31.538720: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5557a3098130 executing computations on platform Host. Devices:
2019-02-25 02:05:31.538756: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
"""
I think I used all default setting in configure (XLA disabled). Do you know what these mean or how I can turn it off? Code can run with no problem, though.

**Comment by lakshayg** [comment]
Glad you were able to do that. Those messages are just info messages. You can follow this https://stackoverflow.com/a/42121886/3033441 to disable them. I also managed to compile a binary, will upload it shortly, you can give it a try.

**Comment by lakshayg** [comment]
https://github.com/lakshayg/tensorflow-build/releases/download/tf1.13.0-ubuntu16.04-py3-avx512f/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl

**Comment by kinoc** [comment]
When I try that one my system complains about wanting 1.13. I noticed the actual file name is tensorflow-1.12.0-..... , so might that be an issue ? 

> tensorflow-gpu 1.13.1 has requirement tensorboard<1.14.0,>=1.13.0, but you'll have tensorboard 1.12.2 which is incompatible.

I was using :

> python3 -m pip install --ignore-installed --upgrade "https://github.com/lakshayg/tensorflow-build/releases/download/tf1.13.0-ubuntu16.04-py3-avx512f/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl"
