### ISSUE TITLE
Supports FMA, AVX, AVX2, SSE4.1, SSE4.2 Means?

### ISSUE THREAD

**Issue by piaobuliao** [lakshayg/tensorflow-build-archived#54]
Supports FMA, AVX, AVX2, SSE4.1, SSE4.2  Means CPU
must support all these: FMA, AVX, AVX2, SSE4.1, SSE4.2 can run the tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl.
if the cpu only support SSE4.1, SSE4.2  ,can not run the tensorflow-1.12.0-cp36-cp36m-linux_x86_64.whl?

**Comment by lakshayg** [comment]
Yes, that is correct

**Comment by piaobuliao** [comment]
@lakshayg  Thank you Very Much
