### ISSUE TITLE
Using Ubuntu build on Arch

### ISSUE THREAD

**Issue by AlexMuresan** [lakshayg/tensorflow-build-archived#55]
is it possible to install the Ubuntu build on my Arch system or do I need to compile it myself?

**Comment by lakshayg** [comment]
You can give it a try but I don't think it is going to work. To get it to work, I believe you need to have the same versions of various libs used by this binary including libc++. You will need to compile it for yourself.

**Comment by AlexMuresan** [comment]
So I tried this on my setup, using conda virtual envs, and it seems to work.
I'm leaving this here in case anyone else has the same question.

My setup:
```
os: Antergos Linux x86_64 (Arch based)
gcc --version: gcc (GCC) 8.2.1 20181127
python --version: Python 3.6.5 :: Anaconda, Inc.
```

Tensorflow-build version I used:
`1.12.0 | Ubuntu 18.04 | 7.3 | 3.6.5 | FMA, AVX, AVX2, SSE4.1, SSE4.2`

**Comment by lakshayg** [comment]
Thanks


________________________________
