### ISSUE TITLE
tensorflow-1.13.1-cp36-cp36m-macosx_10_13_x86_64.whl is not compiled for macOS

### ISSUE THREAD

**Issue by komodovaran** [lakshayg/tensorflow-build-archived#59]
And Mojave is actually macOS version 10.14.

**Comment by lakshayg** [comment]
Correct, Mojave is 10.14 and I too noticed this discrepancy in the version number when I compiled it. It seems to work fine on Mojave, do let me know if you face any issues with the binary.

**Comment by komodovaran** [comment]
Sorry, that was my point. Pip says unsupported platform when trying to install the file.

**Comment by lakshayg** [comment]
Try this: https://github.com/lakshayg/tensorflow-build/releases/download/tf1.13.1-ubuntu16.04-py3/tensorflow-1.13.1-cp37-cp37m-macosx_10_9_x86_64.whl

**Comment by komodovaran** [comment]
Thanks, that one worked!
