### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by waissbluth** [lakshayg/tensorflow-build-archived#6]
Hello,

I'm getting an `Illegal instruction: 4` error message when running tensorflow from the two (python 2.7.13 and 3.6.1) wheels on macOS Sierra (10.12.5).

Any ideas on what the problem might be? According to [this SO answer](https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10) this is due to running on an older system than used to compile, but I'm using the latest (non-beta) OS.

Could it be that my system does not support AVX2?

Thanks!

**Comment by lakshayg** [comment]
@waissbluth Yes, you are right. I just checked and found that the system does not support AVX2. I will update the wheels shortly. Thanks!

**Comment by waissbluth** [comment]
Thanks, that solved the issue! I realized that I don't have FMA support though, but that was expected.

    2017-07-11 22:23:19.310625: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use FMA instructions, but these aren't available on your machine.
    Abort trap: 6

**Comment by lakshayg** [comment]
Just uploaded TF without FMA and AVX2
