### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by borovikovd** [lakshayg/tensorflow-build-archived#60]
Hello,

Very cool project, I use it a lot. 

Unfortunately, It seems that the link in this row is broken:

| TF    | HW  | OS                | GCC              | Python | Supports                                            |                                                                                                                                                                                |
|-------|-----|-------------------|------------------|--------|-----------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1.13.0 | CPU | Ubuntu 16.04     | 5.4 | 3.6.5  | FMA, AVX2, AVX512F              | [Download](https://github.com/lakshayg/tensorflow-build/releases/download/tf1.13.0-ubuntu16.04-py3-avx512f/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl) |

Package name: tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl

The table says it's for python 3.6 but the package name says cp35, i.e. CPython 3.5. Also, the version in the package name doesn't match the version in "TF" column. It's 1.12.0 but should be 1.13.0.

I hope it is easy to fix and I look forward to a corrected link 'cause it would be really nice to use it in our projects!

Cheers,
Denis

**Comment by lakshayg** [comment]
Thanks for reporting the incorrect entry. I have more recent versions of TF on the page now, you should give those a try
