### ISSUE TITLE
Problem in installing tensorflow-build

### ISSUE THREAD

**Issue by Veereshdammur** [lakshayg/tensorflow-build-archived#61]
I am receeving this following error while installing tensorflow-build.
I am using Ubuntu 18.04 with tensorflow -1.9.0

` pip install --ignore-installed --upgrade /home/ifm-veeresh/Downloads/tensorflow-1.9.0-cp36-cp36m-linux_x86_64.whl --user
tensorflow-1.9.0-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.
`

**Comment by lakshayg** [comment]
Are you using python 3.6?

**Comment by Veereshdammur** [comment]
I use python 3.7.3

**Comment by lakshayg** [comment]
This binary is for python 3.6

**Comment by Veereshdammur** [comment]
okay, thanks. I will try by creating a new environment.

**Comment by lakshayg** [comment]
Just added a binary for ubuntu 18.04, python 3.7 https://github.com/lakshayg/tensorflow-build/releases/download/tf-1.14-ubuntu18.04-py3.7/tensorflow-1.14.1-cp37-cp37m-linux_x86_64.whl
