### ISSUE TITLE
TF1.13 Ubuntu 18.04 Python 3.7

### ISSUE THREAD

**Issue by oldani** [lakshayg/tensorflow-build-archived#62]
Could you add this one with `FMA, AVX2, AVX512F`, it's already on Mojave.

Thanks in advance

**Comment by lakshayg** [comment]
Since 1.14 is the latest, I added that https://github.com/lakshayg/tensorflow-build/releases/download/tf-1.14-ubuntu18.04-py3.7/tensorflow-1.14.1-cp37-cp37m-linux_x86_64.whl

**Comment by chaotianjiao** [comment]
@lakshayg can https://github.com/lakshayg/tensorflow-build/releases/download/tf-1.14-ubuntu18.04-py3.7/tensorflow-1.14.1-cp37-cp37m-linux_x86_64.whl  work on MacOS?(python -version 3.7.4)

**Comment by chaotianjiao** [comment]
@lakshayg Hi! Is there any plan to support **tf-1.14-MacOS-py3.7**
macOS mojave-10.14.6 
tensorflow-1.14 
python - 3.7.4

**Comment by lakshayg** [comment]
@chaotianjiao I just added 2 new binaries for macOS

**Comment by chaotianjiao** [comment]
@lakshayg Thank you! I have successfully run pip install --ignore-installed --upgrade /path/to/binary.whl --user like this
![image](https://user-images.githubusercontent.com/42534375/63502751-c8bcd080-c500-11e9-95de-628860d7ebb3.png)
but when I use tensorflow I still have this:
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
