### ISSUE TITLE
Can I trouble you to upload the compiled file of Tensorflow2.0 for ubuntu1604?

### ISSUE THREAD

**Issue by PingJixiang** [lakshayg/tensorflow-build-archived#70]
I used to compile source code on my computer, but it always breaks during compilation and reports errors！ Thank you very much！！！

**Comment by lakshayg** [comment]
https://github.com/lakshayg/tensorflow-build/releases/download/tf-2.1.0-py35-ubuntu1604/tensorflow-2.1.0-cp35-cp35m-linux_x86_64.whl
